In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn import preprocessing
from sklearn.preprocessing import PolynomialFeatures
import scipy.stats as stats
%matplotlib inline


def sum_of_square(vec_a, vec_b):
    diff = vec_a - vec_b
    diff_squared = np.square(diff)
    return (np.sum(diff_squared))

df_june = pd.read_csv("C:\\Users\\ShaukatAbidi\\Documents\\shaukat_python_progs\\eto_experiment\\data_eto\\data_respository\\loc_1\\sampled_each_hour\\WeatherData_loc1_june2016.csv")
df_july = pd.read_csv("C:\\Users\\ShaukatAbidi\\Documents\\shaukat_python_progs\\eto_experiment\\data_eto\\data_respository\\loc_1\\sampled_each_hour\\WeatherData_loc1_july2016.csv")
df_aug = pd.read_csv("C:\\Users\\ShaukatAbidi\\Documents\\shaukat_python_progs\\eto_experiment\\data_eto\\data_respository\\loc_1\\sampled_each_hour\\WeatherData_loc1_aug2016.csv")
df_sep = pd.read_csv("C:\\Users\\ShaukatAbidi\\Documents\\shaukat_python_progs\\eto_experiment\\data_eto\\data_respository\\loc_1\\sampled_each_hour\\WeatherData_loc1_sep2016.csv")
df_oct = pd.read_csv("C:\\Users\\ShaukatAbidi\\Documents\\shaukat_python_progs\\eto_experiment\\data_eto\\data_respository\\loc_1\\sampled_each_hour\\WeatherData_loc1_oct2016.csv")
df_nov = pd.read_csv("C:\\Users\\ShaukatAbidi\\Documents\\shaukat_python_progs\\eto_experiment\\data_eto\\data_respository\\loc_1\\sampled_each_hour\\WeatherData_loc1_nov2016.csv")



In [41]:
df = pd.concat([df_june,df_july,df_aug,df_sep,df_oct,df_nov], axis=0)
df.reset_index(inplace=True)

In [42]:
df

index  ObservationId   Timestamp  ParentLocationId  RelatedLocationId  \
0         0             24  1467086400                 1              94008   
1         1             23  1467090000                 1              94008   
2         2             22  1467093600                 1              94008   
3         3             21  1467097200                 1              94008   
4         4             20  1467100800                 1              94008   
5         5             19  1467104400                 1              94008   
6         6             18  1467108000                 1              94008   
7         7             17  1467111600                 1              94008   
8         8             16  1467115200                 1              94008   
9         9             15  1467118800                 1              94008   
10       10             14  1467122400                 1              94008   
11       11             13  1467126000                 1              94008   
12       12             12  1467129600                 1              94008   
13       13             11  1467133200                 1              94008   
14       14             10  1467136800                 1              94008   
15       15              9  1467140400                 1              94008   
16       16              8  1467144000                 1              94008   
17       17              7  1467147600                 1              94008   
18       18              6  1467151200                 1              94008   
19       19              5  1467154800                 1              94008   
20       20              4  1467158400                 1              94008   
21       21              3  1467162000                 1              94008   
22       22              2  1467165600                 1              94008   
23       23              1  1467169200                 1              94008   
24       24             25  1467172800                 1              94008   
25       25             26  1467176400                 1              94008   
26       26             27  1467180000                 1              94008   
27       27             28  1467183600                 1              94008   
28       28             29  1467187200                 1              94008   
29       29             30  1467190800                 1              94008   
...     ...            ...         ...               ...                ...   
3628    618         351128  1480144800                 1              94008   
3629    619         351292  1480147200                 1              94008   
3630    620         351550  1480151400                 1              94008   
3631    621         351803  1480155600                 1              94008   
3632    622         351957  1480158000                 1              94008   
3633    623         352181  1480161600                 1              94008   
3634    624         352367  1480165200                 1              94008   
3635    625         352578  1480168800                 1              94008   
3636    626         352816  1480173000                 1              94008   
3637    627         352988  1480176000                 1              94008   
3638    628         353223  1480179600                 1              94008   
3639    629         353418  1480183200                 1              94008   
3640    630         353656  1480186800                 1              94008   
3641    631         353859  1480190400                 1              94008   
3642    632         354059  1480194000                 1              94008   
3643    633         354280  1480197600                 1              94008   
3644    634         354537  1480201200                 1              94008   
3645    635         354751  1480205400                 1              94008   
3646    636         354984  1480208400                 1

In [4]:
df.describe()

index  ObservationId     Timestamp  ParentLocationId  \
count  3658.000000    3658.000000  3.658000e+03            3658.0   
mean    355.196555   89515.605249  1.473668e+09               1.0   
std     211.896960  111609.097651  3.800712e+06               0.0   
min       0.000000       1.000000  1.467086e+09               1.0   
25%     171.000000     939.000000  1.470377e+09               1.0   
50%     354.000000   20044.500000  1.473669e+09               1.0   
75%     536.750000  171416.000000  1.476957e+09               1.0   
max     743.000000  357198.000000  1.480248e+09               1.0   

       RelatedLocationId      ReadingId  Temperature    FeelsLike  \
count        3658.000000    3658.000000  3658.000000  3658.000000   
mean        94008.040186  121996.993439    11.191635     9.384828   
std             0.917888  158373.895649     3.718915     4.489018   
min         94008.000000       1.000000     1.000000    -3.200000   
25%         94008.000000    2196.000000     8.800000     6.600000   
50%         94008.000000   18052.000000    11.100000     9.200000   
75%         94008.000000  236702.500000    13.500000    11.800000   
max         94029.000000  504750.000000    26.700001    26.799999   

          DewPoint  RelativeHumidity  WindDirection    WindSpeed     WindGust  \
count  3658.000000       3658.000000    3658.000000  3658.000000  3657.000000   
mean      4.614106         65.777747     249.461728    17.976490    25.538419   
std       3.086815         15.593187     107.317962     9.413219    13.526828   
min      -5.300000         19.000000       0.000000     0.000000     0.000000   
25%       2.500000         54.000000     181.000000    11.000000    15.000000   
50%       4.600000         65.000000     300.000000    17.000000    24.000000   
75%       6.700000         77.000000     330.000000    24.000000    33.000000   
max      15.800000        100.000000     360.000000    76.000000   104.000000   

       RainSince9am     Pressure  RainfallLastHour  RainfallLast10Minutes  
count   3658.000000  3644.000000       3658.000000            3658.000000  
mean       0.617223  1009.661087          0.022909               0.022909  
std        1.879620    10.118926          0.173529               0.173529  
min        0.000000   975.000000          0.000000               0.000000  
25%        0.000000  1004.000000          0.000000               0.000000  
50%        0.000000  1010.000000          0.000000               0.000000  
75%        0.200000  1016.000000          0.000000               0.000000  
max       24.400000  1034.000000          3.800000               3.800000

In [43]:
df_gfs = pd.read_csv("C:\\Users\\ShaukatAbidi\\Documents\\shaukat_python_progs\\eto_experiment\\data_eto\\gfs_data\\gfs\\gfs_combined.csv")


In [44]:
df_gfs

Unnamed: 0  pred_cloud_cover   pred_dewp  pred_lw_rad  \
0     2016-06-01 00:00:00+00:00               NaN  275.700012          NaN   
1     2016-06-01 03:00:00+00:00               0.0  276.100006        258.0   
2     2016-06-01 06:00:00+00:00              12.0  277.899994        264.0   
3     2016-06-01 09:00:00+00:00              37.0  275.700012        258.0   
4     2016-06-01 12:00:00+00:00              21.0  274.200012        254.0   
5     2016-06-01 15:00:00+00:00              16.0  272.799988        249.0   
6     2016-06-01 18:00:00+00:00               6.0  272.000000        247.0   
7     2016-06-01 21:00:00+00:00              44.0  272.899994        247.0   
8     2016-06-02 00:00:00+00:00              32.0  272.600006        249.0   
9     2016-06-02 03:00:00+00:00              24.0  271.600006        255.0   
10    2016-06-02 06:00:00+00:00              54.0  271.700012        259.0   
11    2016-06-02 09:00:00+00:00              63.0  273.799988        251.0   
12    2016-06-02 12:00:00+00:00               7.0  273.100006        249.0   
13    2016-06-02 15:00:00+00:00               1.0  272.600006        250.0   
14    2016-06-02 18:00:00+00:00               5.0  272.700012        258.0   
15    2016-06-02 21:00:00+00:00              69.0  272.899994        297.0   
16    2016-06-03 00:00:00+00:00              31.0  276.100006        267.0   
17    2016-06-03 03:00:00+00:00              23.0  279.200012        278.0   
18    2016-06-03 06:00:00+00:00               9.0  280.899994        284.0   
19    2016-06-03 09:00:00+00:00               2.0  279.799988        277.0   
20    2016-06-03 12:00:00+00:00               0.0  278.899994        273.0   
21    2016-06-03 15:00:00+00:00               0.0  278.000000        268.0   
22    2016-06-03 18:00:00+00:00               0.0  276.899994        264.0   
23    2016-06-03 21:00:00+00:00               0.0  276.000000        260.0   
24    2016-06-04 00:00:00+00:00              50.0  280.100006        264.0   
25    2016-06-04 03:00:00+00:00              62.0  282.299988        296.0   
26    2016-06-04 06:00:00+00:00              88.0  283.100006        316.0   
27    2016-06-04 09:00:00+00:00              98.0  283.200012        318.0   
28    2016-06-04 12:00:00+00:00             100.0  284.799988        338.0   
29    2016-06-04 15:00:00+00:00             100.0  286.000000        354.0   
...                         ...               ...         ...          ...   
1497  2016-12-05 03:00:00+00:00               1.0  278.600006        296.0   
1498  2016-12-05 06:00:00+00:00               1.0  277.600006        298.0   
1499  2016-12-05 09:00:00+00:00               0.0  280.700012        294.0   
1500  2016-12-05 12:00:00+00:00              72.0  282.399994        340.0   
1501  2016-12-05 15:00:00+00:00              88.0  282.300018        353.0   
1502  2016-12-05 18:00:00+00:00              96.0  281.800018        325.0   
1503  2016-12-05 21:00:00+00:00               4.0  277.600006        271.0   
1504  2016-12-06 00:00:00+00:00              90.0  276.300018        299.0   
1505  2016-12-06 03:00:00+00:00              86.0  278.800018        329.0   
1506  2016-12-06 06:00:00+00:00              98.0  282.300018        353.0   
1507  2016-12-06 09:00:00+00:00              67.0  278.000000        310.0   
1508  2016-12-06 12:00:00+00:00               1.0  277.399994        270.0   
1509  2016-12-06 15:00:00+00:00               1.0  277.100006        264.0   
1510  2016-12-06 18:00:00+00:00              59.0  276.899994        276.0   
1511  2016-12-06 21:00:00+00:00              23.0  276.800018        275.0   
1512  2016-12-07 00:00:00+00:00              83.0  276.300018        299.0   
1513  2016-12-07 03:00:00+00:00              95.0  276.200012        333.0   
1514  2016-12-07 06:00:00+00:00              55.0  276.649994        323.0   
1515  2016-12-07 09:00:00+00:00              11.0  277.500000        288.0   
1516  2016-12-07 12:00:00+00:00            

In [45]:
df_gfs.set_index('Unnamed: 0', inplace=True)

In [46]:
df_gfs.index = pd.to_datetime(df_gfs.index)

In [47]:
df_gfs.index

DatetimeIndex(['2016-06-01 00:00:00', '2016-06-01 03:00:00',
               '2016-06-01 06:00:00', '2016-06-01 09:00:00',
               '2016-06-01 12:00:00', '2016-06-01 15:00:00',
               '2016-06-01 18:00:00', '2016-06-01 21:00:00',
               '2016-06-02 00:00:00', '2016-06-02 03:00:00',
               ...
               '2016-12-07 15:00:00', '2016-12-07 18:00:00',
               '2016-12-07 21:00:00', '2016-12-08 00:00:00',
               '2016-12-08 03:00:00', '2016-12-08 06:00:00',
               '2016-12-08 09:00:00', '2016-12-08 12:00:00',
               '2016-12-08 15:00:00', '2016-12-08 18:00:00'],
              dtype='datetime64[ns]', name=u'Unnamed: 0', length=1527, freq=None)

In [48]:
# Generate date with hourly gaps
start_date = '2016-06-01'
end_date = '2016-12-09'
date_range = pd.date_range(start_date, end_date, freq='H')

In [49]:
df_gfs_hourly = pd.DataFrame(index=date_range, columns=df_gfs.columns)

In [50]:
df_gfs_hourly

pred_cloud_cover pred_dewp pred_lw_rad pred_merid_wind  \
2016-06-01 00:00:00              NaN       NaN         NaN             NaN   
2016-06-01 01:00:00              NaN       NaN         NaN             NaN   
2016-06-01 02:00:00              NaN       NaN         NaN             NaN   
2016-06-01 03:00:00              NaN       NaN         NaN             NaN   
2016-06-01 04:00:00              NaN       NaN         NaN             NaN   
2016-06-01 05:00:00              NaN       NaN         NaN             NaN   
2016-06-01 06:00:00              NaN       NaN         NaN             NaN   
2016-06-01 07:00:00              NaN       NaN         NaN             NaN   
2016-06-01 08:00:00              NaN       NaN         NaN             NaN   
2016-06-01 09:00:00              NaN       NaN         NaN             NaN   
2016-06-01 10:00:00              NaN       NaN         NaN             NaN   
2016-06-01 11:00:00              NaN       NaN         NaN             NaN   
2016-06-01 12:00:00              NaN       NaN         NaN             NaN   
2016-06-01 13:00:00              NaN       NaN         NaN             NaN   
2016-06-01 14:00:00              NaN       NaN         NaN             NaN   
2016-06-01 15:00:00              NaN       NaN         NaN             NaN   
2016-06-01 16:00:00              NaN       NaN         NaN             NaN   
2016-06-01 17:00:00              NaN       NaN         NaN             NaN   
2016-06-01 18:00:00              NaN       NaN         NaN             NaN   
2016-06-01 19:00:00              NaN       NaN         NaN             NaN   
2016-06-01 20:00:00              NaN       NaN         NaN             NaN   
2016-06-01 21:00:00              NaN       NaN         NaN             NaN   
2016-06-01 22:00:00              NaN       NaN         NaN             NaN   
2016-06-01 23:00:00              NaN       NaN         NaN             NaN   
2016-06-02 00:00:00              NaN       NaN         NaN             NaN   
2016-06-02 01:00:00              NaN       NaN         NaN             NaN   
2016-06-02 02:00:00              NaN       NaN         NaN             NaN   
2016-06-02 03:00:00              NaN       NaN         NaN             NaN   
2016-06-02 04:00:00              NaN       NaN         NaN             NaN   
2016-06-02 05:00:00              NaN       NaN         NaN             NaN   
...                              ...       ...         ...             ...   
2016-12-07 19:00:00              NaN       NaN         NaN             NaN   
2016-12-07 20:00:00              NaN       NaN         NaN             NaN   
2016-12-07 21:00:00              NaN       NaN         NaN             NaN   
2016-12-07 22:00:00              NaN       NaN         NaN             NaN   
2016-12-07 23:00:00              NaN       NaN         NaN             NaN   
2016-12-08 00:00:00              NaN       NaN         NaN             NaN   
2016-12-08 01:00:00              NaN       NaN         NaN             NaN   
2016-12-08 02:00:00              NaN       NaN         NaN             NaN   
2016-12-08 03:00:00              NaN       NaN         NaN             NaN   
2016-12-08 04:00:00              NaN       NaN         NaN             NaN   
2016-12-08 05:00:00              NaN       NaN         NaN             NaN   
2016-12-08 06:00:00              NaN       NaN         NaN             NaN   
2016-12-08 07:00:00              NaN       NaN         NaN             NaN   
2016-12-08 08:00:00              NaN       NaN         NaN             NaN   
2016-12-08 09:00:00              NaN       NaN         NaN             NaN   
2016-12-08 10:00:00              NaN       NaN         NaN             NaN   
2016-12-08 11:00:00              NaN       NaN         NaN             NaN   
2016-12-08 12:00:00              NaN       NaN         NaN             NaN   
2016-12-08 13:00:00              NaN       NaN         NaN             NaN   
2016-12-08 14:00:00              NaN      

In [51]:
# Copy df_gfs into df_gfs_hourly
tot_len = len(df_gfs)
# ind =  df_gfs.index[1]
# print ind, len(df_gfs)

for entry in range(0,tot_len):
    ind = df_gfs.index[entry]
    df_gfs_hourly.loc[ind] = df_gfs.loc[ind]

# df_gfs_hourly.loc[ind]


In [52]:
df_gfs_hourly

pred_cloud_cover pred_dewp pred_lw_rad pred_merid_wind  \
2016-06-01 00:00:00              NaN     275.7         NaN           -1.58   
2016-06-01 01:00:00              NaN       NaN         NaN             NaN   
2016-06-01 02:00:00              NaN       NaN         NaN             NaN   
2016-06-01 03:00:00                0     276.1         258           -1.75   
2016-06-01 04:00:00              NaN       NaN         NaN             NaN   
2016-06-01 05:00:00              NaN       NaN         NaN             NaN   
2016-06-01 06:00:00               12     277.9         264           -0.33   
2016-06-01 07:00:00              NaN       NaN         NaN             NaN   
2016-06-01 08:00:00              NaN       NaN         NaN             NaN   
2016-06-01 09:00:00               37     275.7         258           -1.42   
2016-06-01 10:00:00              NaN       NaN         NaN             NaN   
2016-06-01 11:00:00              NaN       NaN         NaN             NaN   
2016-06-01 12:00:00               21     274.2         254              -2   
2016-06-01 13:00:00              NaN       NaN         NaN             NaN   
2016-06-01 14:00:00              NaN       NaN         NaN             NaN   
2016-06-01 15:00:00               16     272.8         249           -1.77   
2016-06-01 16:00:00              NaN       NaN         NaN             NaN   
2016-06-01 17:00:00              NaN       NaN         NaN             NaN   
2016-06-01 18:00:00                6       272         247           -1.67   
2016-06-01 19:00:00              NaN       NaN         NaN             NaN   
2016-06-01 20:00:00              NaN       NaN         NaN             NaN   
2016-06-01 21:00:00               44     272.9         247           -1.04   
2016-06-01 22:00:00              NaN       NaN         NaN             NaN   
2016-06-01 23:00:00              NaN       NaN         NaN             NaN   
2016-06-02 00:00:00               32     272.6         249           -0.64   
2016-06-02 01:00:00              NaN       NaN         NaN             NaN   
2016-06-02 02:00:00              NaN       NaN         NaN             NaN   
2016-06-02 03:00:00               24     271.6         255            0.22   
2016-06-02 04:00:00              NaN       NaN         NaN             NaN   
2016-06-02 05:00:00              NaN       NaN         NaN             NaN   
...                              ...       ...         ...             ...   
2016-12-07 19:00:00              NaN       NaN         NaN             NaN   
2016-12-07 20:00:00              NaN       NaN         NaN             NaN   
2016-12-07 21:00:00               45     279.7         315           -4.18   
2016-12-07 22:00:00              NaN       NaN         NaN             NaN   
2016-12-07 23:00:00              NaN       NaN         NaN             NaN   
2016-12-08 00:00:00              101     281.7         353            -1.3   
2016-12-08 01:00:00              NaN       NaN         NaN             NaN   
2016-12-08 02:00:00              NaN       NaN         NaN             NaN   
2016-12-08 03:00:00               92     278.5         349           -0.22   
2016-12-08 04:00:00              NaN       NaN         NaN             NaN   
2016-12-08 05:00:00              NaN       NaN         NaN             NaN   
2016-12-08 06:00:00               80     277.1         335            0.95   
2016-12-08 07:00:00              NaN       NaN         NaN             NaN   
2016-12-08 08:00:00              NaN       NaN         NaN             NaN   
2016-12-08 09:00:00               50    275.46         296            0.54   
2016-12-08 10:00:00              NaN       NaN         NaN             NaN   
2016-12-08 11:00:00              NaN       NaN         NaN             NaN   
2016-12-08 12:00:00                4     275.3         264           -0.82   
2016-12-08 13:00:00              NaN       NaN         NaN             NaN   
2016-12-08 14:00:00              NaN      

In [56]:
df_gfs_hourly

pred_cloud_cover pred_dewp pred_lw_rad pred_merid_wind  \
2016-06-01 00:00:00              NaN     275.7         NaN           -1.58   
2016-06-01 01:00:00              NaN       NaN         NaN             NaN   
2016-06-01 02:00:00              NaN       NaN         NaN             NaN   
2016-06-01 03:00:00                0     276.1         258           -1.75   
2016-06-01 04:00:00              NaN       NaN         NaN             NaN   
2016-06-01 05:00:00              NaN       NaN         NaN             NaN   
2016-06-01 06:00:00               12     277.9         264           -0.33   
2016-06-01 07:00:00              NaN       NaN         NaN             NaN   
2016-06-01 08:00:00              NaN       NaN         NaN             NaN   
2016-06-01 09:00:00               37     275.7         258           -1.42   
2016-06-01 10:00:00              NaN       NaN         NaN             NaN   
2016-06-01 11:00:00              NaN       NaN         NaN             NaN   
2016-06-01 12:00:00               21     274.2         254              -2   
2016-06-01 13:00:00              NaN       NaN         NaN             NaN   
2016-06-01 14:00:00              NaN       NaN         NaN             NaN   
2016-06-01 15:00:00               16     272.8         249           -1.77   
2016-06-01 16:00:00              NaN       NaN         NaN             NaN   
2016-06-01 17:00:00              NaN       NaN         NaN             NaN   
2016-06-01 18:00:00                6       272         247           -1.67   
2016-06-01 19:00:00              NaN       NaN         NaN             NaN   
2016-06-01 20:00:00              NaN       NaN         NaN             NaN   
2016-06-01 21:00:00               44     272.9         247           -1.04   
2016-06-01 22:00:00              NaN       NaN         NaN             NaN   
2016-06-01 23:00:00              NaN       NaN         NaN             NaN   
2016-06-02 00:00:00               32     272.6         249           -0.64   
2016-06-02 01:00:00              NaN       NaN         NaN             NaN   
2016-06-02 02:00:00              NaN       NaN         NaN             NaN   
2016-06-02 03:00:00               24     271.6         255            0.22   
2016-06-02 04:00:00              NaN       NaN         NaN             NaN   
2016-06-02 05:00:00              NaN       NaN         NaN             NaN   
...                              ...       ...         ...             ...   
2016-12-07 19:00:00              NaN       NaN         NaN             NaN   
2016-12-07 20:00:00              NaN       NaN         NaN             NaN   
2016-12-07 21:00:00               45     279.7         315           -4.18   
2016-12-07 22:00:00              NaN       NaN         NaN             NaN   
2016-12-07 23:00:00              NaN       NaN         NaN             NaN   
2016-12-08 00:00:00              101     281.7         353            -1.3   
2016-12-08 01:00:00              NaN       NaN         NaN             NaN   
2016-12-08 02:00:00              NaN       NaN         NaN             NaN   
2016-12-08 03:00:00               92     278.5         349           -0.22   
2016-12-08 04:00:00              NaN       NaN         NaN             NaN   
2016-12-08 05:00:00              NaN       NaN         NaN             NaN   
2016-12-08 06:00:00               80     277.1         335            0.95   
2016-12-08 07:00:00              NaN       NaN         NaN             NaN   
2016-12-08 08:00:00              NaN       NaN         NaN             NaN   
2016-12-08 09:00:00               50    275.46         296            0.54   
2016-12-08 10:00:00              NaN       NaN         NaN             NaN   
2016-12-08 11:00:00              NaN       NaN         NaN             NaN   
2016-12-08 12:00:00                4     275.3         264           -0.82   
2016-12-08 13:00:00              NaN       NaN         NaN             NaN   
2016-12-08 14:00:00              NaN      

In [62]:
# For interpolation, fill the first row of df_gfs_hourly
df_gfs_hourly.iloc[0] = df_gfs_hourly.iloc[3]


In [66]:
df_gfs_hourly.describe()

pred_cloud_cover    pred_dewp  pred_lw_rad  pred_merid_wind  pred_pe  \
count             1527.0  1527.000000       1527.0          1527.00   1527.0   
unique             102.0   250.000000        150.0           735.00    855.0   
top                100.0   277.600006        263.0            -1.61     -1.0   
freq               213.0    27.000000         30.0             9.00     12.0   

        pred_rain_rate  pred_soil_moisture_lower  pred_soil_moisture_upper  \
count           1527.0                  1527.000                   1527.00   
unique           187.0                   138.000                    218.00   
top                0.0                     0.187                      0.17   
freq            1053.0                    55.000                     61.00   

        pred_sunshine  pred_surface_pressure  pred_sw_rad    pred_temp  \
count          1527.0            1527.000000       1527.0  1527.000000   
unique          120.0            1523.000000        336.0   545.000000   
top               0.0           99630.085938          0.0   282.399994   
freq            674.0               2.000000        636.0    20.000000   

        pred_zonal_wind  
count           1527.00  
unique           828.00  
top                1.12  
freq               8.00

In [72]:
# df_gfs_hourly['pred_cloud_cover']
for col in df_gfs_hourly:
    # print col
    df_gfs_hourly[col] = pd.to_numeric(df_gfs_hourly[col])

In [74]:
# df_gfs_hourly.dtypes
# now interpolate
df_gfs_hourly = df_gfs_hourly.interpolate(method='time')

In [4]:
# Adding variables to pandas dataframe
df['y_t_1'] = df.Temperature.shift(-1) # y_(t+1)
df['y_t_2'] = df.Temperature.shift(-2) # y_(t+2)
df['y_t_3'] = df.Temperature.shift(-3) # y_(t+3)
df['y_t_4'] = df.Temperature.shift(-4) # y_(t+4)
df['y_t_5'] = df.Temperature.shift(-5) # y_(t+5)

# Adding past variables of order_1 (o1)

# columns=['time_index', 'FeelsLike', 'DewPoint', 'RelativeHumidity', 'WindSpeed', 
#          'WindGust', 'RainSince9am', 'Pressure', 'RainfallLastHour', 'RainfallLast10Minutes'])

df['FeelsLike_o1'] = df.FeelsLike.shift(1) # t-1
df['DewPoint_o1'] = df.DewPoint.shift(1) # t-1
df['RelativeHumidity_o1'] = df.RelativeHumidity.shift(1) # t-1
df['WindSpeed_o1'] = df.WindSpeed.shift(1) # t-1
df['WindGust_o1'] = df.WindGust.shift(1) # t-1
df['RainSince9am_o1'] = df.RainSince9am.shift(1) # t-1
df['Pressure_o1'] = df.Pressure.shift(1) # t-1
df['RainfallLastHour_o1'] = df.RainfallLastHour.shift(1) # t-1
df['RainfallLast10Minutes_o1'] = df.RainfallLast10Minutes.shift(1) # t-1



In [5]:
# df
# df.to_csv("C:\\Users\\ShaukatAbidi\\Documents\\shaukat_python_progs\\eto_experiment\\data_eto\\data_respository\\loc_1\\sampled_each_hour\\check.csv")

In [6]:
# Drop nans
df = df.dropna()
df.reset_index(inplace=True)
df.to_csv("C:\\Users\\ShaukatAbidi\\Documents\\shaukat_python_progs\\eto_experiment\\data_eto\\data_respository\\loc_1\\sampled_each_hour\\check.csv")

In [7]:
y_gt = df.as_matrix(columns=['Temperature'])

tot_points = y_gt.shape[0]
train_points = 2265 # training until september
test_points = tot_points - train_points
print(tot_points, train_points, test_points)

(3623L, 2265, 1358L)


In [8]:
df_train = df.loc[0:train_points]
df_test = df.loc[train_points + 1:tot_points]
#df.head(6)
# df
# print(linear_model.LinearRegression.__doc__)
# df.keys()

In [9]:
df_test

level_0  index  ObservationId   Timestamp  ParentLocationId  \
2266     2296     30          82081  1475348400                 1   
2267     2297     31          82324  1475352600                 1   
2268     2298     32          82485  1475355600                 1   
2269     2299     33          82750  1475359200                 1   
2270     2300     34          82899  1475362800                 1   
2271     2301     35          83111  1475366400                 1   
2272     2302     36          83267  1475369400                 1   
2273     2303     37          83515  1475373600                 1   
2274     2304     38          83750  1475377800                 1   
2275     2305     39          83905  1475381400                 1   
2276     2306     40          84068  1475384400                 1   
2277     2307     41          84283  1475388000                 1   
2278     2308     42          84495  1475392200                 1   
2279     2309     43          84685  1475395800                 1   
2280     2310     44          84828  1475399400                 1   
2281     2311     45          85049  1475402400                 1   
2282     2312     46          85228  1475405400                 1   
2283     2313     47          85433  1475410200                 1   
2284     2314     48          85621  1475413200                 1   
2285     2315     49          85843  1475416800                 1   
2286     2316     50          86110  1475421000                 1   
2287     2317     51          86259  1475424000                 1   
2288     2318     52          86471  1475427600                 1   
2289     2319     53          86696  1475431200                 1   
2290     2320     54          86944  1475435400                 1   
2291     2321     55          87122  1475438400                 1   
2292     2322     56          87358  1475442000                 1   
2293     2323     57          87574  1475445600                 1   
2294     2324     58          87795  1475449800                 1   
2295     2325     59          88003  1475452800                 1   
...       ...    ...            ...         ...               ...   
3593     3623    613         350037  1480125600                 1   
3594     3624    614         350248  1480129200                 1   
3595     3625    615         350372  1480132800                 1   
3596     3626    616         350629  1480136400                 1   
3597     3627    617         350842  1480140000                 1   
3598     3628    618         351128  1480144800                 1   
3599     3629    619         351292  1480147200                 1   
3600     3630    620         351550  1480151400                 1   
3601     3631    621         351803  1480155600                 1   
3602     3632    622         351957  1480158000                 1   
3603     3633    623         352181  1480161600                 1   
3604     3634    624         352367  1480165200                 1   
3605     3635    625         352578  1480168800                 1   
3606     3636    626         352816  1480173000                 1   
3607     3637    627         352988  1480176000                 1   
3608     3638    628         353223  1480179600                 1   
3609     3639    629         353418  1480183200                 1   
3610     3640    630         353656  1480186800                 1   
3611     3641    631         353859  1480190400                 1   
3612     3642    632         354059  1480194000                 1   
3613     3643    633         354280  1480197600                 1   
3614     3644    634         354537  1480201200                 1   
3615     3645    635         354751  1480205400                 1   
3616     3646    636         354984  1480208400                 1   
3617     3647    637         355184  1480212000                 1   
3618     3648    638         355379  1480215600                 1   
3619

In [171]:
# df.to_csv('July2016_pandas_df.csv')

In [10]:
print(y_gt.shape)

(3623L, 1L)


In [11]:
# Dropping variables that are not used for training
df = df.drop('level_0',axis=1)
df = df.drop('index',axis=1)
df = df.drop('ObservationId',axis=1)
df = df.drop('Timestamp',axis=1)
df = df.drop('ParentLocationId',axis=1)
df = df.drop('RelatedLocationId',axis=1)
df = df.drop('ReadingId',axis=1)
df = df.drop('UtcTime',axis=1)
df = df.drop('LocalTime',axis=1)
df = df.drop('TimeZone',axis=1)
df = df.drop('WindDirection',axis=1)
df = df.drop('WindDirectionCompass',axis=1)

In [12]:
df.columns

Index([u'Temperature', u'FeelsLike', u'DewPoint', u'RelativeHumidity',
       u'WindSpeed', u'WindGust', u'RainSince9am', u'Pressure',
       u'RainfallLastHour', u'RainfallLast10Minutes', u'y_t_1', u'y_t_2',
       u'y_t_3', u'y_t_4', u'y_t_5', u'FeelsLike_o1', u'DewPoint_o1',
       u'RelativeHumidity_o1', u'WindSpeed_o1', u'WindGust_o1',
       u'RainSince9am_o1', u'Pressure_o1', u'RainfallLastHour_o1',
       u'RainfallLast10Minutes_o1'],
      dtype='object')

In [13]:
# x = df.as_matrix(columns=['time_index', 'FeelsLike', 'DewPoint', 'RelativeHumidity', 'WindSpeed', 'WindGust', 'RainSince9am', 'Pressure', 'RainfallLastHour', 'RainfallLast10Minutes'])

# x_t1 = df.as_matrix(columns=['time_index', 'RelativeHumidity', 'WindSpeed', 'WindGust', 'Pressure'])
# x_t1 = df.as_matrix(columns=['time_index', 'FeelsLike', 'DewPoint', 'RelativeHumidity', 'WindSpeed', 'WindGust', 'RainSince9am', 'Pressure', 'RainfallLastHour', 'RainfallLast10Minutes'])
# x_t1 = df.as_matrix(columns=['FeelsLike', 'DewPoint', 'RelativeHumidity', 'WindSpeed', 'WindGust', 'RainSince9am', 'Pressure', 'RainfallLastHour', 'RainfallLast10Minutes'])
# x_t1 = df.as_matrix(columns=['FeelsLike', 'DewPoint', 'RelativeHumidity', 'WindSpeed', 'WindGust', 'RainSince9am', 'Pressure', 'RainfallLastHour', 'RainfallLast10Minutes')
x_t1 = df.as_matrix(columns=['FeelsLike', 'DewPoint', 'RelativeHumidity', 'WindSpeed', 'WindGust', 'RainSince9am', 'Pressure', 'RainfallLastHour', 'RainfallLast10Minutes', 'FeelsLike_o1', 'DewPoint_o1', 'RelativeHumidity_o1','WindSpeed_o1', 'WindGust_o1', 'RainSince9am_o1', 'Pressure_o1','RainfallLastHour_o1', 'RainfallLast10Minutes_o1'])


# Do scaling according to min-max scaling
scaler_minmax = preprocessing.MinMaxScaler()
x_t1 = scaler_minmax.fit_transform(x_t1)

# Add polynomials
poly = PolynomialFeatures(degree=2, interaction_only=True)
x_t1 = poly.fit_transform(x_t1)

# get the vectors for five-hour forecast
y_gt_t1 = df.as_matrix(columns=[df.y_t_1.name])
y_gt_t2 = df.as_matrix(columns=[df.y_t_2.name])
y_gt_t3 = df.as_matrix(columns=[df.y_t_3.name])
y_gt_t4 = df.as_matrix(columns=[df.y_t_4.name])
y_gt_t5 = df.as_matrix(columns=[df.y_t_5.name])

print(x_t1.shape)
print(y_gt_t1.shape)
print(y_gt_t2.shape)
print(y_gt_t3.shape)
print(y_gt_t4.shape)
print(y_gt_t5.shape)

(3623L, 172L)
(3623L, 1L)
(3623L, 1L)
(3623L, 1L)
(3623L, 1L)
(3623L, 1L)


In [48]:
# x_t1[743:744,:]
# y_gt_t1[0:744,:]
# print(y_gt_t1.shape[0],y_gt_t1.shape[1])
# print(x_t1[1:2,:])

In [14]:
# Generate Train Sequence
x_t1_train = x_t1[0:train_points + 1,:]
y_gt_t1_train = y_gt_t1[0:train_points + 1,:]
y_gt_t2_train = y_gt_t2[0:train_points + 1,:]
y_gt_t3_train = y_gt_t3[0:train_points + 1,:]
y_gt_t4_train = y_gt_t4[0:train_points + 1,:]
y_gt_t5_train = y_gt_t5[0:train_points + 1,:]




# Generate Test Sequence
x_t1_test = x_t1[train_points + 1:tot_points + 1 ,:]
y_t1_test = y_gt_t1[train_points + 1:tot_points + 1,:]
y_t2_test = y_gt_t2[train_points + 1:tot_points + 1,:]
y_t3_test = y_gt_t3[train_points + 1:tot_points + 1,:]
y_t4_test = y_gt_t4[train_points + 1:tot_points + 1,:]
y_t5_test = y_gt_t5[train_points + 1:tot_points + 1,:]


print(x_t1_train.shape, y_gt_t1_train.shape, y_gt_t2_train.shape, y_gt_t3_train.shape, y_gt_t4_train.shape, y_gt_t5_train.shape)
print(x_t1_test.shape, y_t1_test.shape, y_t2_test.shape, y_t3_test.shape, y_t4_test.shape, y_t5_test.shape)

((2266L, 172L), (2266L, 1L), (2266L, 1L), (2266L, 1L), (2266L, 1L), (2266L, 1L))
((1357L, 172L), (1357L, 1L), (1357L, 1L), (1357L, 1L), (1357L, 1L), (1357L, 1L))


In [39]:
# print(y_gt_t4_train[0:5,:])
# print(x_t1_test[0])
print(y_gt_t1_train)
print(y_t1_test)

[[ 11.5       ]
 [ 11.7       ]
 [ 10.9       ]
 ..., 
 [ 17.10000038]
 [ 17.79999924]
 [ 17.70000076]]
[[ 17.5       ]
 [ 17.10000038]
 [ 16.60000038]
 ..., 
 [ 12.        ]
 [ 10.10000038]
 [  9.69999981]]


In [15]:
# call linear regression for five forecasts
obj_1 = linear_model.LinearRegression()
obj_1.fit(x_t1_train,y_gt_t1_train)

obj_2 = linear_model.LinearRegression()
obj_2.fit(x_t1_train,y_gt_t2_train)

obj_3 = linear_model.LinearRegression()
obj_3.fit(x_t1_train,y_gt_t3_train)

obj_4 = linear_model.LinearRegression()
obj_4.fit(x_t1_train,y_gt_t4_train)

obj_5 = linear_model.LinearRegression()
obj_5.fit(x_t1_train,y_gt_t5_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [16]:
# regression_object.predict(x)[0:5] predict first five data vectors
test_ind = 0;
ybar_1 = obj_1.predict(x_t1_test)[test_ind]
ybar_2 = obj_2.predict(x_t1_test)[test_ind]
ybar_3 = obj_3.predict(x_t1_test)[test_ind]
ybar_4 = obj_4.predict(x_t1_test)[test_ind]
ybar_5 = obj_5.predict(x_t1_test)[test_ind]
print(ybar_1, ybar_2, ybar_3, ybar_4, ybar_5)

# get groundtruth vector
y_gt_vec = np.empty(5)
y_gt_vec[0] = y_t1_test[test_ind]
y_gt_vec[1] = y_t2_test[test_ind]
y_gt_vec[2] = y_t3_test[test_ind]
y_gt_vec[3] = y_t4_test[test_ind]
y_gt_vec[4] = y_t5_test[test_ind]
print(y_gt_vec)

# get prediction vector
y_pred_vec = np.empty(5)
y_pred_vec[0] = ybar_1
y_pred_vec[1] = ybar_2
y_pred_vec[2] = ybar_3
y_pred_vec[3] = ybar_4
y_pred_vec[4] = ybar_5

# print(y_pred_vec)

# print('from function = \n' sum_of_square(y_pred_vec, y_gt_vec))
sse = sum_of_square(y_pred_vec, y_gt_vec)
print('from function, sse = %f\n' %(sse) )

(array([ 17.29560051]), array([ 16.83887169]), array([ 16.17963317]), array([ 15.79222822]), array([ 15.62292653]))
[ 17.5         17.10000038  16.60000038  16.          15.5       ]
from function, sse = 0.344956



In [17]:
print('total test_points = %d\n' %(test_points))
sse_list=[]
for test_instance in range(0,test_points-1):
    test_ind = test_instance
    ybar_1 = obj_1.predict(x_t1_test)[test_ind]
    ybar_2 = obj_2.predict(x_t1_test)[test_ind]
    ybar_3 = obj_3.predict(x_t1_test)[test_ind]
    ybar_4 = obj_4.predict(x_t1_test)[test_ind]
    ybar_5 = obj_5.predict(x_t1_test)[test_ind]
    print('ex# %d: ' %(test_instance))
    # print(ybar_1, ybar_2, ybar_3, ybar_4, ybar_5)

    # get groundtruth vector
    y_gt_vec = np.empty(5)
    y_gt_vec[0] = y_t1_test[test_ind]
    y_gt_vec[1] = y_t2_test[test_ind]
    y_gt_vec[2] = y_t3_test[test_ind]
    y_gt_vec[3] = y_t4_test[test_ind]
    y_gt_vec[4] = y_t5_test[test_ind]
    print(y_gt_vec)

    # get prediction vector
    y_pred_vec = np.empty(5)
    y_pred_vec[0] = ybar_1
    y_pred_vec[1] = ybar_2
    y_pred_vec[2] = ybar_3
    y_pred_vec[3] = ybar_4
    y_pred_vec[4] = ybar_5

    print(y_pred_vec)

    # print('from function = \n' sum_of_square(y_pred_vec, y_gt_vec))
    sse = sum_of_square(y_pred_vec, y_gt_vec)
    sse_list.append(sse)
    print('sse = %f\n' %(sse) )
    

total test_points = 1358

ex# 0: 
[ 17.5         17.10000038  16.60000038  16.          15.5       ]
[ 17.29560051  16.83887169  16.17963317  15.79222822  15.62292653]
sse = 0.344956

ex# 1: 
[ 17.10000038  16.60000038  16.          15.5         15.39999962]
[ 17.40244632  17.06496421  16.53975432  16.04936206  15.61256343]
sse = 0.945982

ex# 2: 
[ 16.60000038  16.          15.5         15.39999962  15.30000019]
[ 16.20295851  15.49806299  14.60125187  14.00233117  13.62089274]
sse = 5.990210

ex# 3: 
[ 16.          15.5         15.39999962  15.30000019  14.69999981]
[ 15.86815991  15.14518107  14.53882113  13.82451868  13.32863408]
sse = 4.942596

ex# 4: 
[ 15.5         15.39999962  15.30000019  14.69999981  13.69999981]
[ 15.63366524  15.15681563  14.46651952  14.04960439  13.67314824]
sse = 1.195430

ex# 5: 
[ 15.39999962  15.30000019  14.69999981  13.69999981  14.19999981]
[ 15.01949677  14.41904488  13.83721991  13.32728688  12.97102888]
sse = 3.314538

ex# 6: 
[ 15.30000019  14.

In [26]:
# sum(sse_list)
#  sse_list

[0.13034275896530945,
 0.34495598197950389,
 0.9459816806796173,
 5.9902101252231805,
 4.9425963127630554,
 1.1954300872818269,
 3.3145383096263483,
 0.53968837841619044,
 2.2843700038045789,
 5.5401555622315666,
 1.136245509977752,
 4.1365906643777119,
 3.3966979656671734,
 0.93621722354095849,
 2.7236856347768348,
 4.3656400818564141,
 6.5393681183438028,
 21.280624031840503,
 46.468650608510742,
 90.743187629326627,
 14.586226324374993,
 5.7662697692305036,
 3.9100764302867397,
 3.0125342910762236,
 8.1337331634490546,
 2.8241172228062177,
 7.0391549897032686,
 11.641196246959689,
 3.2889120999185435,
 0.83614701920695,
 0.29150787333672606,
 12.221744488168476,
 2.6865234691511124,
 2.681012297474493,
 2.1094928455184743,
 8.943397685702088,
 39.917943597761088,
 50.041391607402389,
 81.999956896724456,
 100.19159828110122,
 97.766590877057837,
 75.670455100122524,
 40.063744684784936,
 46.590699263942653,
 22.203091026437786,
 10.809387462786656,
 8.5725980648623228,
 9.6923749742

In [22]:
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [58]:
# create model
model = Sequential()
model.add(Dense(200, input_dim=172, init='normal', activation='relu')) #1st Hidden Layer
model.add(Dense(100, init='normal', activation='relu')) #2nd Hidden Layer
model.add(Dense(10, init='normal', activation='relu')) #3rd Hidden Layer
model.add(Dense(5, init='normal')) #output layer
    
# compile model
model.compile(loss='mean_squared_error', optimizer='adam')

In [31]:
Y = np.concatenate( (y_gt_t1_train,y_gt_t2_train,y_gt_t3_train,y_gt_t4_train,y_gt_t5_train) , axis=1)

In [39]:
print x_t1_train.shape, Y.shape

(2266L, 172L) (2266L, 5L)


In [59]:
model.fit(x_t1_train, Y, nb_epoch=100, verbose=1, shuffle=True)

Epoch 1/100
2266/2266 [==============================] - 0s - loss: 68.0308     
Epoch 2/100
2266/2266 [==============================] - 0s - loss: 8.2338     
Epoch 3/100
2266/2266 [==============================] - 0s - loss: 6.4463     
Epoch 4/100
2266/2266 [==============================] - 0s - loss: 5.6458     
Epoch 5/100
2266/2266 [==============================] - 0s - loss: 5.2244     
Epoch 6/100
2266/2266 [==============================] - 0s - loss: 4.9088     
Epoch 7/100
2266/2266 [==============================] - 0s - loss: 4.7248     
Epoch 8/100
2266/2266 [==============================] - 0s - loss: 4.5769     
Epoch 9/100
2266/2266 [==============================] - 0s - loss: 4.4466     
Epoch 10/100
2266/2266 [==============================] - 0s - loss: 4.3530     
Epoch 11/100
2266/2266 [==============================] - 0s - loss: 4.2580     
Epoch 12/100
2266/2266 [==============================] - 0s - loss: 4.2155     
Epoch 13/100
2266/2266 [============

In [61]:
model.predict(x_t1_train)

array([[ 12.42255306,  12.24092293,  12.06326675,  11.77379608,
         11.52485466],
       [ 11.68884182,  11.43313885,  11.2049427 ,  10.90916157,
         10.64204502],
       [ 12.04987335,  11.88766193,  11.73742485,  11.47677326,
         11.25261211],
       ..., 
       [ 16.1272049 ,  15.94693184,  15.69143963,  15.19068718,
         14.77281189],
       [ 16.5370369 ,  16.35944557,  16.09464455,  15.56391335,
         15.12271786],
       [ 16.81130981,  16.61624718,  16.32713699,  15.76511097,  15.2964859 ]], dtype=float32)

In [64]:
model.summary

<bound method Sequential.summary of <keras.models.Sequential object at 0x0000000011BE6A58>>