In [36]:
import numpy as np
import netCDF4
import matplotlib.pyplot as plt
import datetime as dt
import pandas as pd
import os

%matplotlib inline


In [37]:
def l2_norm_of_difference(vec_a, vec_b):
    return np.linalg.norm(vec_a - vec_b)

In [38]:
def get_lat_lon_not_to_use_this(lat_0_array, lon_0_array, target_lat, target_lon):
    idx_lat = 55555
    idx_lon = 55555

    
    # Making sure we are passing correct ranges of lat and lon
    if ( (target_lat <= -10.0 and target_lat >= -44.0) and (target_lon <= 154.0 and target_lon >= 112.0) ):
        idx_lat = np.argmin(np.abs(lat_0_array - target_lat))
        idx_lon = np.argmin(np.abs(lon_0_array - target_lon))
        
        print 'idx_lat: ', idx_lat, 'value in NetCDF: ', lat_0_array[idx_lat], 'given lat: ', target_lat
        print 'idx_lon: ', idx_lon, 'value in NetCDF: ', lon_0_array[idx_lon], 'given lon: ', target_lon
    
    return idx_lat,idx_lon

In [39]:
def get_lat_lon(lat_0_array, lon_0_array, target_lat, target_lon):
    # initialize variables
    idx_lat = 55555
    idx_lon = 55555
    val_lat = 0.0
    val_lon = 0.0
    lat_lon_vec = np.array([0.0,0.0])
    start = True
    least_norm = 0.0
    
    # Making sure we are passing correct ranges of lat and lon
    if ( (target_lat <= -10.0 and target_lat >= -44.0) and (target_lon <= 154.0 and target_lon >= 112.0) ):
        target_lat_lon_vec = np.array([target_lat, target_lon])
        
        # Going for very quick implementation (NOT OPTIMIZED/ Slow)
        for _lat in range(0,len(lat_0_array)):
            for _lon in range(0,len(lon_0_array)):
                # print 'idx: ', _lat, 'val: ', lat_0_array[_lat]
                # print 'idx: ', _lon, 'val: ', lon_0_array[_lon]
                if(start):
                    start = False
                    # Prepare lat/lon vec
                    lat_lon_vec[0] = lat_0_array[_lat]
                    lat_lon_vec[1] = lon_0_array[_lon]
                    
                    # prepare vars to return with l2_distance
                    least_norm = l2_norm_of_difference(lat_lon_vec, target_lat_lon_vec)
                    
                    # to return 
                    idx_lat = _lat
                    idx_lon = _lon
                    val_lat = lat_0_array[idx_lat]
                    val_lon = lon_0_array[idx_lon]
                    
                    print 'Start--', 'idx_lat: ', idx_lat, 'NetCDF lat: ', val_lat, 'target lat: ', target_lat
                    print 'idx_lon: ', idx_lon, 'NetCDF lon: ', val_lon, 'given lon: ', target_lon
                    print 'norm: ', least_norm
                    print '\n'
                    
                else:
                    # Prepare lat/lon vec
                    lat_lon_vec[0] = lat_0_array[_lat]
                    lat_lon_vec[1] = lon_0_array[_lon]
                    
                    # prepare vars to return with l2_distance
                    l2_norm = l2_norm_of_difference(lat_lon_vec, target_lat_lon_vec)
                    
                    if(l2_norm < least_norm):
                        least_norm = l2_norm
                        # to return
                        idx_lat = _lat
                        idx_lon = _lon
                        val_lat = lat_0_array[idx_lat]
                        val_lon = lon_0_array[idx_lon]
        
        
    
    print 'End--', 'idx_lat: ', idx_lat, 'NetCDF lat: ', val_lat, 'target lat: ', target_lat
    print 'idx_lon: ', idx_lon, 'NetCDF lon: ', val_lon, 'given lon: ', target_lon
    print 'norm: ', least_norm
    print '\n'
                    
    return idx_lat, idx_lon, val_lat, val_lon  


In [40]:
# Target lat/lon
target_lat = -42.8897
target_lon =  147.3278


# Read NETCDF File 
# Check Netcdf
data = netCDF4.Dataset('C:/Users/ShaukatAbidi/Downloads/datafiles_1600_1799/extracted_files/gfs.0p25.2015031406.f000.grib2.abrie233580.nc')
            
# Get lat/lon
lat_0_array = data.variables['lat_0'][:]
lon_0_array = data.variables['lon_0'][:]
idx_lat,idx_lon, val_lat, val_lon = get_lat_lon(lat_0_array, lon_0_array, target_lat, target_lon)

print 'target_lat: ',target_lat,'target_lon: ',target_lon 
print 'calculated_lat: ',val_lat,'calculated_lon: ',val_lon 


Start-- idx_lat:  0 NetCDF lat:  -10.0 target lat:  -42.8897
idx_lon:  0 NetCDF lon:  112.0 given lon:  147.3278
norm:  48.2678549236


End-- idx_lat:  132 NetCDF lat:  -43.0 target lat:  -42.8897
idx_lon:  141 NetCDF lon:  147.25 given lon:  147.3278
norm:  0.134977516646


target_lat:  -42.8897 target_lon:  147.3278
calculated_lat:  -43.0 calculated_lon:  147.25


In [35]:
lon_0_array[idx_lon]

148.25

In [8]:
lon_0_array.shape

(169L,)

In [9]:
lat_0_array

array([-10.  , -10.25, -10.5 , -10.75, -11.  , -11.25, -11.5 , -11.75,
       -12.  , -12.25, -12.5 , -12.75, -13.  , -13.25, -13.5 , -13.75,
       -14.  , -14.25, -14.5 , -14.75, -15.  , -15.25, -15.5 , -15.75,
       -16.  , -16.25, -16.5 , -16.75, -17.  , -17.25, -17.5 , -17.75,
       -18.  , -18.25, -18.5 , -18.75, -19.  , -19.25, -19.5 , -19.75,
       -20.  , -20.25, -20.5 , -20.75, -21.  , -21.25, -21.5 , -21.75,
       -22.  , -22.25, -22.5 , -22.75, -23.  , -23.25, -23.5 , -23.75,
       -24.  , -24.25, -24.5 , -24.75, -25.  , -25.25, -25.5 , -25.75,
       -26.  , -26.25, -26.5 , -26.75, -27.  , -27.25, -27.5 , -27.75,
       -28.  , -28.25, -28.5 , -28.75, -29.  , -29.25, -29.5 , -29.75,
       -30.  , -30.25, -30.5 , -30.75, -31.  , -31.25, -31.5 , -31.75,
       -32.  , -32.25, -32.5 , -32.75, -33.  , -33.25, -33.5 , -33.75,
       -34.  , -34.25, -34.5 , -34.75, -35.  , -35.25, -35.5 , -35.75,
       -36.  , -36.25, -36.5 , -36.75, -37.  , -37.25, -37.5 , -37.75,
      

In [10]:
lon_0_array

array([ 112.  ,  112.25,  112.5 ,  112.75,  113.  ,  113.25,  113.5 ,
        113.75,  114.  ,  114.25,  114.5 ,  114.75,  115.  ,  115.25,
        115.5 ,  115.75,  116.  ,  116.25,  116.5 ,  116.75,  117.  ,
        117.25,  117.5 ,  117.75,  118.  ,  118.25,  118.5 ,  118.75,
        119.  ,  119.25,  119.5 ,  119.75,  120.  ,  120.25,  120.5 ,
        120.75,  121.  ,  121.25,  121.5 ,  121.75,  122.  ,  122.25,
        122.5 ,  122.75,  123.  ,  123.25,  123.5 ,  123.75,  124.  ,
        124.25,  124.5 ,  124.75,  125.  ,  125.25,  125.5 ,  125.75,
        126.  ,  126.25,  126.5 ,  126.75,  127.  ,  127.25,  127.5 ,
        127.75,  128.  ,  128.25,  128.5 ,  128.75,  129.  ,  129.25,
        129.5 ,  129.75,  130.  ,  130.25,  130.5 ,  130.75,  131.  ,
        131.25,  131.5 ,  131.75,  132.  ,  132.25,  132.5 ,  132.75,
        133.  ,  133.25,  133.5 ,  133.75,  134.  ,  134.25,  134.5 ,
        134.75,  135.  ,  135.25,  135.5 ,  135.75,  136.  ,  136.25,
        136.5 ,  136

In [14]:
for _lat in range(0,len(lat_0_array)):
    print 'idx: ', _lat, 'val: ', lat_0_array[_lat]
del _lat

idx:  0 val:  -10.0
idx:  1 val:  -10.25
idx:  2 val:  -10.5
idx:  3 val:  -10.75
idx:  4 val:  -11.0
idx:  5 val:  -11.25
idx:  6 val:  -11.5
idx:  7 val:  -11.75
idx:  8 val:  -12.0
idx:  9 val:  -12.25
idx:  10 val:  -12.5
idx:  11 val:  -12.75
idx:  12 val:  -13.0
idx:  13 val:  -13.25
idx:  14 val:  -13.5
idx:  15 val:  -13.75
idx:  16 val:  -14.0
idx:  17 val:  -14.25
idx:  18 val:  -14.5
idx:  19 val:  -14.75
idx:  20 val:  -15.0
idx:  21 val:  -15.25
idx:  22 val:  -15.5
idx:  23 val:  -15.75
idx:  24 val:  -16.0
idx:  25 val:  -16.25
idx:  26 val:  -16.5
idx:  27 val:  -16.75
idx:  28 val:  -17.0
idx:  29 val:  -17.25
idx:  30 val:  -17.5
idx:  31 val:  -17.75
idx:  32 val:  -18.0
idx:  33 val:  -18.25
idx:  34 val:  -18.5
idx:  35 val:  -18.75
idx:  36 val:  -19.0
idx:  37 val:  -19.25
idx:  38 val:  -19.5
idx:  39 val:  -19.75
idx:  40 val:  -20.0
idx:  41 val:  -20.25
idx:  42 val:  -20.5
idx:  43 val:  -20.75
idx:  44 val:  -21.0
idx:  45 val:  -21.25
idx:  46 val:  -21.5


In [15]:
for _lon in range(0,len(lon_0_array)):
    print 'idx: ', _lon, 'val: ', lon_0_array[_lon]

idx:  0 val:  112.0
idx:  1 val:  112.25
idx:  2 val:  112.5
idx:  3 val:  112.75
idx:  4 val:  113.0
idx:  5 val:  113.25
idx:  6 val:  113.5
idx:  7 val:  113.75
idx:  8 val:  114.0
idx:  9 val:  114.25
idx:  10 val:  114.5
idx:  11 val:  114.75
idx:  12 val:  115.0
idx:  13 val:  115.25
idx:  14 val:  115.5
idx:  15 val:  115.75
idx:  16 val:  116.0
idx:  17 val:  116.25
idx:  18 val:  116.5
idx:  19 val:  116.75
idx:  20 val:  117.0
idx:  21 val:  117.25
idx:  22 val:  117.5
idx:  23 val:  117.75
idx:  24 val:  118.0
idx:  25 val:  118.25
idx:  26 val:  118.5
idx:  27 val:  118.75
idx:  28 val:  119.0
idx:  29 val:  119.25
idx:  30 val:  119.5
idx:  31 val:  119.75
idx:  32 val:  120.0
idx:  33 val:  120.25
idx:  34 val:  120.5
idx:  35 val:  120.75
idx:  36 val:  121.0
idx:  37 val:  121.25
idx:  38 val:  121.5
idx:  39 val:  121.75
idx:  40 val:  122.0
idx:  41 val:  122.25
idx:  42 val:  122.5
idx:  43 val:  122.75
idx:  44 val:  123.0
idx:  45 val:  123.25
idx:  46 val:  123.5


In [24]:
lat_lon_vec = np.array([1,2])
target_lat_lon_vec = np.array([target_lat, target_lon])
print lat_lon_vec, lat_lon_target_vec, lat_lon_vec-target_lat_lon_vec, l2_norm_of_difference(lat_lon_vec, target_lat_lon_vec)

[1 2] [ -41.26101779  148.166736  ] [  42.26101779 -146.166736  ] 152.153568271


In [26]:
lat_lon_vec

array([1, 2])

In [27]:
lat_lon_vec[0] = -5
lat_lon_vec

array([-5,  2])